# Cloud Build configuration for ShareView Platform

substitutions:
  _REGION: europe-west2
  _SERVICE_NAME: shareview-platform
  _SV_CLOUD_SQL_CONNECTION_NAME: retailer-sales-rpt:europe-west2:shareview-db
  _RSR_CLOUD_SQL_CONNECTION_NAME: retailer-sales-rpt:europe-west2:rsr-db

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
      - '.'
    timeout: 1200s

  # Step 2: Push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '60s'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,AUTH_TRUST_HOST=true,SV_CLOUD_SQL_CONNECTION_NAME=${_SV_CLOUD_SQL_CONNECTION_NAME},RSR_CLOUD_SQL_CONNECTION_NAME=${_RSR_CLOUD_SQL_CONNECTION_NAME},SV_DBNAME=shareview,RSR_DBNAME=retailer_analytics'
      - '--set-secrets'
      - 'SV_DBUSER=SV_DBUSER:latest,SV_DBPASSWORD=SV_DBPASSWORD:latest,RSR_DBUSER=RSR_DBUSER:latest,RSR_DBPASSWORD=RSR_DBPASSWORD:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,NEXTAUTH_URL=NEXTAUTH_URL:latest'
      - '--add-cloudsql-instances'
      - '${_SV_CLOUD_SQL_CONNECTION_NAME},${_RSR_CLOUD_SQL_CONNECTION_NAME}'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s

images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
