'use client'

import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertCircle, RefreshCcw, Trophy, AlertTriangle, Sparkles, XCircle, Filter, Info } from 'lucide-react'
import { PageHeadline, QuickStatsBar, InsightsPanel } from '@/components/shared'
import { useDateRange } from '@/lib/contexts/DateRangeContext'
import SearchTermsSubTabs from '@/components/client/SearchTermsSubTabs'
import KeywordPerformanceTable from '@/components/client/KeywordPerformanceTable'
import ComingSoonPanel from '@/components/client/ComingSoonPanel'
import WordAnalysis from '@/components/client/WordAnalysis'
import type { PageInsightsResponse } from '@/types'

interface KeywordsTabProps {
  retailerId: string
  apiBase?: string
  retailerConfig?: { insights?: boolean; market_insights?: boolean; word_analysis?: boolean }
  visibleMetrics?: string[]
  isAdminView?: boolean
  reportId?: number
  reportPeriod?: { start: string; end: string; type: string }
}

interface KeywordPerformance {
  search_term: string
  total_impressions: number
  total_clicks: number
  total_conversions: number
  ctr: number
  conversion_rate: number
  performance_tier: string
  first_seen: string
  last_seen: string
  days_active?: number
}

interface KeywordSummary {
  unique_search_terms: number
  total_impressions: number
  total_clicks: number
  total_conversions: number
  terms_with_conversions: number
  terms_with_clicks: number
  overall_ctr: number
  overall_cvr: number
  overall_conversion_rate: number
  tier_star: number
  tier_strong: number
  tier_underperforming: number
  tier_poor: number
}

interface MetricCardData {
  label: string
  value: string | number
  change?: number
  changeUnit?: '%' | 'pp' | ''
  status?: 'success' | 'warning' | 'critical' | 'neutral'
  subtitle?: string
}

interface QuadrantKeyword {
  search_term: string
  impressions: number
  clicks: number
  conversions: number
  ctr: number
  cvr: number
}

interface Quadrants {
  winners: QuadrantKeyword[]
  css_wins_retailer_loses: QuadrantKeyword[]
  hidden_gems: QuadrantKeyword[]
  poor_performers: QuadrantKeyword[]
  median_ctr: number
  qualified_count?: number
  qualification?: {
    min_impressions?: number
    min_clicks?: number
    fallback_applied?: boolean
    fallback_reason?: 'qualified_count' | 'positive_count' | 'both' | null
    base_min_impressions?: number
    base_min_clicks?: number
    fallback_min_impressions?: number
    fallback_min_clicks?: number
    trigger_qualified_count?: number
    trigger_positive_count?: number
    positive_count?: number
  } | null
}

interface KeywordsResponse {
  keywords: KeywordPerformance[]
  summary: KeywordSummary
  metricCards: MetricCardData[]
  quadrants?: Quadrants
}

function formatPeriod(period: string): string {
  const [year, month] = period.split('-').map(Number)
  const d = new Date(year, month - 1)
  return d.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })
}

export default function KeywordsTab({ retailerId, apiBase, retailerConfig, visibleMetrics, isAdminView = false, reportId, reportPeriod }: KeywordsTabProps) {
  const { period, periodType, start, end, setPeriod } = useDateRange()
  const [activeSubTab, setActiveSubTab] = useState('performance')
  const [selectedQuadrant, setSelectedQuadrant] = useState<'winners' | 'css_wins_retailer_loses' | 'hidden_gems' | 'poor_performers'>('winners')
  const [glossaryOpen, setGlossaryOpen] = useState(true)
  const [keywordsData, setKeywordsData] = useState<KeywordsResponse | null>(null)
  const [insights, setInsights] = useState<PageInsightsResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [nearestBefore, setNearestBefore] = useState<string | null>(null)
  const [nearestAfter, setNearestAfter] = useState<string | null>(null)

  const features = retailerConfig || { insights: true, market_insights: true, word_analysis: true }
  const showMarketComparisonTab = features.market_insights !== false || isAdminView
  const marketComparisonHiddenForRetailer = isAdminView && features.market_insights === false
  const showWordAnalysisTab = features.word_analysis !== false || isAdminView
  const wordAnalysisHiddenForRetailer = isAdminView && features.word_analysis === false
  const allowedTabs = useMemo(() => {
    return [
      'performance',
      ...(showWordAnalysisTab ? ['word-analysis'] : []),
      ...(showMarketComparisonTab ? ['market-comparison'] : []),
      ...(features.insights !== false ? ['insights'] : []),
    ]
  }, [features.insights, showMarketComparisonTab, showWordAnalysisTab])

  const metricCardTooltips: Record<string, string> = {
    'Total Impressions': 'Total times the selected search terms were shown during this period.',
    Impressions: 'Total times the selected search terms were shown during this period.',
    'Total Clicks': 'Total clicks generated by the selected search terms during this period.',
    Clicks: 'Total clicks generated by the selected search terms during this period.',
    'Total Conversions': 'Total conversions attributed to the selected search terms during this period.',
    Conversions: 'Total conversions attributed to the selected search terms during this period.',
    'Conversion Rate': 'Conversions divided by clicks for the selected search-term set.',
    CVR: 'Conversions divided by clicks for the selected search-term set.',
    'Click-through Rate': 'Clicks divided by impressions for the selected search-term set.',
    CTR: 'Clicks divided by impressions for the selected search-term set.',
  }

  // Initialize sub-tab from URL params
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const initialTab = params.get('searchTermsSubTab') || 'performance'
    setActiveSubTab(allowedTabs.includes(initialTab) ? initialTab : 'performance')
  }, [allowedTabs])

  // Fallback if tab becomes unavailable
  useEffect(() => {
    if (!allowedTabs.includes(activeSubTab)) {
      setActiveSubTab('performance')
    }
  }, [activeSubTab, allowedTabs])

  // Update URL when sub-tab changes
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    params.set('searchTermsSubTab', activeSubTab)
    window.history.replaceState(null, '', `${window.location.pathname}?${params.toString()}`)
  }, [activeSubTab])

  const fetchInsights = useCallback(async (tab: string) => {
    const base = apiBase ?? '/api'
    const response = await fetch(
      `${base}/page-insights?retailerId=${retailerId}&pageType=search-terms&tab=${tab}&period=${period}`
    )

    if (!response.ok) {
      throw new Error('Unable to load insights')
    }

    return (await response.json()) as PageInsightsResponse
  }, [apiBase, period, retailerId])

  const loadData = async () => {
    try {
      setLoading(true)
      setError(null)
      setNearestBefore(null)
      setNearestAfter(null)

      const keywordsResponse = await fetch(`${apiBase ?? '/api'}/retailers/${retailerId}/keywords?period=${period}`, {
        credentials: 'include',
        cache: 'no-store',
      })

      if (!keywordsResponse.ok) {
        if (keywordsResponse.status === 404) {
          const body = await keywordsResponse.json().catch(() => ({}))
          setNearestBefore(body.nearest_before ?? null)
          setNearestAfter(body.nearest_after ?? null)
          setKeywordsData(null)
          return
        }
        throw new Error('Unable to load search terms data')
      }

      const keywordsJson = (await keywordsResponse.json()) as KeywordsResponse
      setKeywordsData(keywordsJson)
    } catch (fetchError) {
      setError(fetchError instanceof Error ? fetchError.message : 'Unable to load search terms data')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (!retailerId) return
    loadData()
  }, [retailerId, period])

  useEffect(() => {
    let cancelled = false

    const loadInsights = async () => {
      const shouldFetchInsights = activeSubTab === 'insights' || activeSubTab === 'market-comparison'
      if (!shouldFetchInsights) {
        setInsights(null)
        return
      }

      try {
        const payload = await fetchInsights(activeSubTab === 'market-comparison' ? 'market-insights' : activeSubTab)
        if (!cancelled) {
          setInsights(payload)
        }
      } catch {
        if (!cancelled) {
          setInsights(null)
        }
      }
    }

    loadInsights()

    return () => {
      cancelled = true
    }
  }, [activeSubTab, fetchInsights])

  return (
    <div className="space-y-5">
      <SearchTermsSubTabs
        activeSubTab={activeSubTab}
        onSubTabChange={setActiveSubTab}
        retailerConfig={features}
        marketComparisonHiddenForRetailer={marketComparisonHiddenForRetailer}
        wordAnalysisHiddenForRetailer={wordAnalysisHiddenForRetailer}
      />

      {loading ? (
        <div className="space-y-8">
          <div className="h-12 rounded-lg bg-gray-200 animate-pulse" />
          <div className="h-24 rounded-lg bg-gray-200 animate-pulse" />
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {Array.from({ length: 4 }).map((_, idx) => (
              <div key={idx} className="h-24 rounded-lg bg-gray-200 animate-pulse" />
            ))}
          </div>
          <div className="h-64 rounded-lg bg-gray-200 animate-pulse" />
        </div>
      ) : error ? (
        <div className="space-y-6">
          <div className="bg-white rounded-lg border border-gray-200 p-6">
            <div className="flex items-start gap-3 text-amber-600">
              <AlertCircle className="w-5 h-5 mt-0.5" />
              <div className="flex-1">
                <h3 className="font-semibold">Search terms data unavailable</h3>
                <p className="text-sm text-gray-600 mt-1">{error}</p>
                <button
                  type="button"
                  onClick={loadData}
                  className="mt-4 inline-flex items-center gap-2 rounded-md border border-gray-300 px-3 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50"
                >
                  <RefreshCcw className="w-4 h-4" />
                  Retry
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : !keywordsData ? (
        <div className="bg-white rounded-lg border border-gray-200 p-6 text-center text-sm text-gray-500">
          <p className="mb-1">No data available for this period.</p>
          {(nearestBefore || nearestAfter) && (
            <div className="mt-3 flex items-center justify-center gap-3">
              {nearestBefore && (
                <button
                  onClick={() => setPeriod(nearestBefore)}
                  className="inline-flex items-center gap-1 rounded-md bg-gray-50 border border-gray-300 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-100 transition-colors"
                >
                  ← {formatPeriod(nearestBefore)}
                </button>
              )}
              {nearestAfter && (
                <button
                  onClick={() => setPeriod(nearestAfter)}
                  className="inline-flex items-center gap-1 rounded-md bg-gray-50 border border-gray-300 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-100 transition-colors"
                >
                  {formatPeriod(nearestAfter)} →
                </button>
              )}
            </div>
          )}
        </div>
      ) : (
        <>
      {activeSubTab === 'performance' && (
        <>
          {keywordsData.metricCards && keywordsData.metricCards.length > 0 && (() => {
            const labelToKey: Record<string, string> = {
              'Total Impressions': 'impressions',
              Impressions: 'impressions',
              'Total Clicks': 'clicks',
              Clicks: 'clicks',
              'Total Conversions': 'conversions',
              Conversions: 'conversions',
              'Conversion Rate': 'cvr',
              CVR: 'cvr',
              'Click-through Rate': 'ctr',
              CTR: 'ctr',
            }
            const visibleCards = (keywordsData.metricCards || []).filter(card => {
              if (!visibleMetrics?.length) return true
              const key = labelToKey[card.label]
              return !key || visibleMetrics.includes(key)
            })
            if (!visibleCards.length) return null
            return (
              <QuickStatsBar
                items={visibleCards.map(card => ({
                  label: card.label,
                  value: typeof card.value === 'number' ? String(card.value) : card.value,
                  change: card.change ?? undefined,
                  subtitle: card.subtitle,
                  tooltip: metricCardTooltips[card.label],
                }))}
              />
            )
          })()}

          {keywordsData.quadrants && (() => {
            const qualification = keywordsData.quadrants?.qualification
            const baseMinImpressions = qualification?.base_min_impressions ?? 50
            const baseMinClicks = qualification?.base_min_clicks ?? 5
            const activeMinImpressions = qualification?.min_impressions ?? baseMinImpressions
            const activeMinClicks = qualification?.min_clicks ?? baseMinClicks
            const fallbackApplied = qualification?.fallback_applied === true
            const fallbackMinImpressions = qualification?.fallback_min_impressions ?? 30
            const fallbackMinClicks = qualification?.fallback_min_clicks ?? 3
            const triggerQualifiedCount = qualification?.trigger_qualified_count ?? 30
            const triggerPositiveCount = qualification?.trigger_positive_count ?? 20
            const qualifiedCount = keywordsData.quadrants?.qualified_count ?? 0
            const positiveCount = qualification?.positive_count
            const medianCtr = keywordsData.quadrants?.median_ctr ?? 0

            return (
              <>
                {glossaryOpen && (
                  <div className="rounded-lg border border-gray-200 bg-white p-4">
                    <div className="mb-3 flex items-center justify-between">
                      <span className="text-sm font-semibold text-gray-700">How the Search Terms lists are selected</span>
                      <button
                        type="button"
                        onClick={() => setGlossaryOpen(false)}
                        className="text-gray-500 transition-colors hover:text-gray-700"
                        aria-label="Hide Search Terms explanation"
                      >
                        <XCircle className="h-5 w-5" />
                      </button>
                    </div>

                    <div className="space-y-2 text-sm text-gray-700">
                      <p>
                        A month can contain thousands of search terms, but many are too low-activity to be useful.
                        We first keep terms that pass a minimum activity bar, then split them into four focused groups.
                      </p>
                      <p>
                        Qualification cutoff used this month: at least {activeMinImpressions.toLocaleString()} impressions and {activeMinClicks.toLocaleString()} clicks per term.
                        {' '}(standard: {baseMinImpressions.toLocaleString()} impressions and {baseMinClicks.toLocaleString()} clicks).
                      </p>
                      {fallbackApplied && (
                        <p>
                          Low-volume fallback was applied, so the cutoff was relaxed to {fallbackMinImpressions.toLocaleString()} impressions and {fallbackMinClicks.toLocaleString()} clicks.
                          This is triggered when qualified terms are below {triggerQualifiedCount.toLocaleString()} or conversion-positive terms are below {triggerPositiveCount.toLocaleString()}.
                        </p>
                      )}
                      <p>
                        CTR split point this month: {medianCtr.toFixed(2)}% (the median CTR of qualified terms).
                        Terms are split into high CTR vs low CTR around this point, and then by converting vs non-converting.
                      </p>
                      <p>
                        To keep this decision-ready, each table filter is capped:
                        High CTR &amp; High Conversions (max 150),
                        Low CTR &amp; High Conversions (max 150),
                        High CTR, Low Conversions (max 100),
                        Low CTR, Low Conversions (max 100).
                      </p>
                      <p>
                        Qualified terms considered: {qualifiedCount.toLocaleString()}
                        {typeof positiveCount === 'number' ? `; of these, ${positiveCount.toLocaleString()} had at least one conversion.` : '.'}
                        {' '}The remaining terms are usually low-signal or near the middle, so they add volume but not much decision value.
                      </p>
                    </div>
                  </div>
                )}

                {!glossaryOpen && (
                  <div className="flex justify-end">
                    <button
                      type="button"
                      onClick={() => setGlossaryOpen(true)}
                      className="text-gray-500 transition-colors hover:text-gray-700"
                      aria-label="Show Search Terms explanation"
                    >
                      <Info className="h-5 w-5" />
                    </button>
                  </div>
                )}
              </>
            )
          })()}

          {keywordsData.quadrants && (() => {
            const quadrants = [
              {
                key: 'winners' as const,
                label: 'High CTR & High Conversions',
                icon: Trophy,
                color: '#2563EB',
              },
              {
                key: 'hidden_gems' as const,
                label: 'Low CTR & High Conversions',
                icon: Sparkles,
                color: '#14B8A6',
              },
              {
                key: 'css_wins_retailer_loses' as const,
                label: 'High CTR, Low Conversions',
                icon: AlertTriangle,
                color: '#F97316',
              },
              {
                key: 'poor_performers' as const,
                label: 'Low CTR, Low Conversions',
                icon: XCircle,
                color: '#DC2626',
              },
            ]
            return (
              <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
                <div className="px-4 py-3 border-b border-gray-200 bg-gray-50">
                  <div className="flex items-center gap-2 mb-2">
                    <Filter className="w-4 h-4 text-gray-500" />
                    <span className="text-sm font-medium text-gray-700">Filter by group:</span>
                  </div>
                  <div className="flex items-center gap-2 flex-wrap">
                    {quadrants.map(({ key, label, icon: Icon, color }) => {
                      const isActive = selectedQuadrant === key
                      return (
                        <button
                          key={key}
                          onClick={() => setSelectedQuadrant(key)}
                          className="px-3 py-1.5 text-sm font-semibold rounded-full border-2 transition-all hover:shadow-md flex items-center gap-1.5"
                          style={isActive ? {
                            backgroundColor: color,
                            borderColor: color,
                            color: 'white',
                          } : {
                            backgroundColor: 'white',
                            borderColor: color,
                            color: color,
                          }}
                        >
                          <Icon className="w-3.5 h-3.5" />
                          {label} ({keywordsData.quadrants![key].length})
                        </button>
                      )
                    })})
                  </div>
                </div>
                <KeywordPerformanceTable
                  keywords={keywordsData.quadrants[selectedQuadrant].map(k => ({
                    search_term: k.search_term,
                    total_impressions: k.impressions,
                    total_clicks: k.clicks,
                    total_conversions: k.conversions,
                    ctr: k.ctr,
                    conversion_rate: k.cvr,
                    performance_tier: selectedQuadrant === 'winners' ? 'star' : selectedQuadrant === 'hidden_gems' ? 'strong' : 'poor',
                    first_seen: '',
                    last_seen: '',
                    days_active: 0,
                  }))}
                  summary={keywordsData.summary}
                  loading={loading}
                  error={error}
                />
              </div>
            )
          })()}
        </>
      )}

      {activeSubTab === 'word-analysis' && (
        reportId ? (
          <ComingSoonPanel className="p-6" />
        ) : (
          <WordAnalysis
            retailerId={retailerId}
            apiBase={apiBase}
            reportId={reportId}
            reportPeriod={reportPeriod}
          />
        )
      )}

      {activeSubTab === 'insights' && insights?.insightsPanel ? (
        <InsightsPanel
          title={insights.insightsPanel.title}
          insights={insights.insightsPanel.insights}
          singleColumn={insights.insightsPanel.singleColumn}
        />
      ) : activeSubTab === 'insights' ? (
        <ComingSoonPanel className="p-6" />
      ) : null}

      {activeSubTab === 'market-comparison' && insights?.insightsPanel ? (
        <InsightsPanel
          title={insights.insightsPanel.title || 'Market Insights'}
          insights={insights.insightsPanel.insights}
          singleColumn={insights.insightsPanel.singleColumn}
        />
      ) : activeSubTab === 'market-comparison' ? (
        <ComingSoonPanel className="p-6" />
      ) : null}
        </>
      )}
    </div>
  )
}
